# SPDX-License-Identifier: Apache-2.0 OR MIT
#
# Modifications Copyright Kani Contributors
# See GitHub history for details.

[package]
name = "member"
version = "0.0.0"
license = "MIT/Apache-2.0"
publish = false

[dependencies.proptest]
path = "../../.."
