# Copyright Kani Contributors
# SPDX-License-Identifier: Apache-2.0 OR MIT

[target.'cfg(all())']
rustflags = [ # Global lints/warnings. Need to use underscore instead of -.

    # Purposefully disabled lints
    "-Aclippy::expect_fun_call",
    "-Aclippy::or_fun_call",
    "-Aclippy::new_without_default",
]

[env]
# This is a hack to get the root of the workspace. TODO: This should
# be removed when cargo implements this. See Kani-side tracking issue
# is https://github.com/model-checking/kani/issues/1472 for details.
CARGO_WORKSPACE_DIR = { value = "", relative = true }
