# Copyright Kani Contributors
# SPDX-License-Identifier: Apache-2.0 OR MIT

[target.'cfg(all())']
rustflags = [ # Global lints/warnings. Need to use underscore instead of -.

    # Purposefully disabled lints
    "-Aclippy::expect_fun_call",
    "-Aclippy::or_fun_call",
    "-Aclippy::new_without_default",
]

[env]
# This is a hack to get the root of the workspace. TODO: This should be
# removed when cargo implements this. See
# https://github.com/rust-lang/cargo/issues/3946#issuecomment-973132993
# for details.
CARGO_WORKSPACE_DIR = { value = "", relative = true }
