# SPDX-License-Identifier: Apache-2.0 OR MIT
#
# Modifications Copyright Kani Contributors
# See GitHub history for details.

[workspace]
members = ["member"]
# Ensure that proptest itself is not dragged in as part of the workspace
exclude = ["../..", "../../.."]
