# Copyright Kani Contributors
# SPDX-License-Identifier: Apache-2.0 OR MIT
name: Kani CI
on: [push, pull_request]

jobs:
  regression:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, ubuntu-18.04, ubuntu-20.04]
    steps:
      - name: Checkout Kani
        uses: actions/checkout@v2

      - name: Setup Kani Dependencies
        uses: ./.github/actions/setup
        with:
            os: ${{ matrix.os }}

      - name: Build Kani
        run: |
          export RUST_BACKTRACE=1
          cargo build --workspace

      - name: Execute Kani regression
        run: ./scripts/kani-regression.sh

